### ISSUE TITLE
portability?

### ISSUE THREAD

**Issue by NeonLightning** [madmodder123/retropie_music_overlay#3]
is it possible to make it use ~/ instead of /home/pi/ because i'd like to use it in TheRA but that uses pigaming instead of pi.

**Comment by madmodder123** [comment]
Done, enjoy

**Comment by madmodder123** [comment]
Let me know if you run into issues

**Comment by NeonLightning** [comment]
bgm toggle hasn't been updated i noticed that much. i haven't had a chance to test the actual script though as i first have to cleanly remove the present sh based bgm script that is included in TheRA.

**Comment by NeonLightning** [comment]
i get this when i try to run it
`Traceback (most recent call last):
  File "/home/pigaming/BGM.py", line 22, in <module>
    screen_width = subprocess.check_output("tvservice -s | grep -m 1 -o '[0-9][0-9][0-9]\+x[0-9][0-9][0-9]\+' | grep -m 1 -o '[0-9][0-9][0-9]\+x' | grep -m 1 -o '[0-9][0-9][0-9]\+'", shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'tvservice -s | grep -m 1 -o '[0-9][0-9][0-9]\+x[0-9][0-9][0-9]\+' | grep -m 1 -o '[0-9][0-9][0-9]\+x' | grep -m 1 -o '[0-9][0-9][0-9]\+'' returned non-zero exit status 1
`

**Comment by madmodder123** [comment]
So I ended up fixing some issues with the "~/" changes and tested it all out so that part should be working fine now. (Be aware I edited some of the code and the rc.local entry is now changed, so you will probably have to edit that.)
I just ordered an ODROID so I can get the other issue fixed (it errors because ODROID doesn't use tvservice for checking screen resolution).
It should be a quick update to have it up and running once I get it in the mail :)

**Comment by madmodder123** [comment]
@NeonLightning I forgot to update this but this should work on the ODROID, I couldn't get the overlay to work but I did add support for the OGST Gaming Console Case that has a screen on it (It will display the song info on it)
